[project]
name = "python-basic-template"
version = "0.1.0"
description = "Basic Python template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
]
